export const CREATE_USER_PROFILE_START = "CREATE_USER_PROFILE_START";
export const CREATE_USER_PROFILE_SAGA = "CREATE_USER_PROFILE_SAGA";
export const CREATE_USER_PROFILE_SUCCESS = "CREATE_USER_PROFILE_SUCCESS";
export const CREATE_USER_PROFILE_FAIL = "CREATE_USER_PROFILE_FAIL";

export const VIEW_PROFILE_START = "VIEW_PROFILE_START";
export const VIEW_PROFILE_SAGA = "VIEW_PROFILE_SAGA";
export const VIEW_PROFILE_SUCCESS = "VIEW_PROFILE_SUCCESS";
export const VIEW_PROFILE_FAIL = "VIEW_PROFILE_FAIL";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SAGA = "UPDATE_PROFILE_SAGA";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PROFILE_PIC_START = "UPDATE_PROFILE_PIC_START";
export const UPDATE_PROFILE_PIC_SAGA = "UPDATE_PROFILE_PIC_SAGA";
export const UPDATE_PROFILE_PIC_SUCCESS = "UPDATE_PROFILE_PIC_SUCCESS";
export const UPDATE_PROFILE_PIC_FAIL = "UPDATE_PROFILE_PIC_FAIL";
