export const STAKER_DATA_START = "STAKER_DATA_START";
export const STAKER_DATA_SAGA = "STAKER_DATA_SAGA";
export const STAKER_DATA_SUCCESS = "STAKER_DATA_SUCCESS";
export const STAKER_DATA_FAIL = "STAKER_DATA_FAIL";

export const BALANCE_START = "BALANCE_START";
export const BALANCE_SAGA = "BALANCE_SAGA";
export const BALANCE_SUCCESS = "BALANCE_SUCCESS";
export const BALANCE_FAIL = "BALANCE_FAIL";